### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by marticliment** [PavlikBender/Pickers#1]
Hello,

I would like to use your code on my open-source project.

Under which license is your project published?

**Comment by PavlikBender** [comment]
@marticliment Don't worry. It's absolutely free, take it, and use how you want. I 've just added MIT License to the project!

**Comment by marticliment** [comment]
Thanks!

Btw, I needed to use also SaveFile picker, and I implemented it. Do you want me to do a PR with the changes to add SaveFile picker functionality?

**Comment by PavlikBender** [comment]
Yes, ofcourse!

**Comment by marticliment** [comment]
@PavlikBender, the implementation on the PR is ready for merge. I have used it on my project [here](https://github.com/marticliment/WingetUI/releases/tag/3.0.0-beta0)
